baseurl = "https://jess-website-4e683.firebaseapp.com/"
languageCode = "en-us"
title = "Jess Garfield Carpentry"
theme = "hugo-creative-theme"

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at http://fontawesome.io/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more information take a look at the README.

	# To provide some metadata for search engines feel free to add some
	# information about you and your website.
	name = "Jess Garfield"
	description = "Website for Jess Garfield -- Creative designer & carpenter on Tamborine Mountain, Queensland, Australia"

	# The path must be relative to the static folder
	favicon = "favicon.ico"


	# Navigation
	[params.navigation]
		brand = "Jess Garfield Carpentry"

		[params.navigation.links]
			about     = "About Jess"
			services  = "Services"
			portfolio = "Portfolio"
			contact   = "Contact"


	# Hero section
	[params.hero]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		slogan     = "Jess Garfield Carpentry"
		subtitle   = "Creative ideas constructed with quality craftmenship."
		buttonText = "About Jess"


	# About section
	[params.about]
		headline    = "Jess Garfield"
		description = "As a Tamborine Mountain local, Jess has been providing honest, quality carpendry services to residents for 15 years -- specialising in decks and patios, shed conversions, bathrooms and kitchens."
		buttonText  = "Get started!"


	# Service section
	[params.services]
		headline = "Quality Craftmenship"

			[[params.services.list]]
				icon = "fa-check"
				title = "Patios and Pagodas"
				description = "Experienced in the precision design & build of patios & pagodas."

      [[params.services.list]]
        icon = "fa-check"
        title = "Bathrooms"
        description = "Jess can design and build your dream bathroom."

			[[params.services.list]]
        icon = "fa-check"
        title = "Shed conversions & granny flats"
        description = "Need extra space? Jess has completed a number of high-quality conversions."

      [[params.services.list]]
        icon = "fa-heart"
        title = "All Made with Love"
        description = "... to specificaton and budget!"

    # Portfolio modals
	[params.portfolio.modal]
        # client = "Client"
        # date = "Date"
        category = "Category"
        buttonText = "Close"

    # Aside section
	# [params.aside]
	# 	headline = "Get the Creative Theme for Hugo"
	#
	# 	[params.aside.button]
	# 		text = "Download now"
	# 		link = "//github.com/digitalcraftsman/hugo-creative-theme"

	# Contact section
	[params.contact]
		headline = "Contact Jess for a free quote"
		description = "Jess would be happy to provide you with a competitive, no-obligation quote. Additional portfolio photos and references available on request."
		phone = "0422 272 463"
		email = "jessgarfield@hotmail.com"
